export const GET_TODOS_REQUEST = 'GET_TODOS_REQUEST';
export const GET_TODOS_SUCCESS = 'GET_TODOS_SUCCESS';
export const POST_TODO_REQUEST = 'POST_TODO_REQUEST';
export const POST_TODO_SUCCESS = 'POST_TODO_SUCCESS';
